name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/toltec-dev/rust
    steps:
      - uses: actions/checkout@v2
      - run: cat /root/.cargo/config
