name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/toltec-dev/toolchain
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: armv7-unknown-linux-gnueabihf
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions/upload-artifact@v2
        with:
          path: target/
